==> paas/logs/paas.log <==
ERROR [2022-04-12 11:00:10] /paas/paas/common/http.py 50 _http_request 317 140530790353640
         http request error! method: GET, url: http://www.bking.com:8073/login/accounts/is_login/, data: {u'bk_token': '1lVUC14z2SZfsIJgs_nX_TsK7dEM6gqrbzmdTUtrG6Q'}
Traceback (most recent call last):
  File "/paas/paas/common/http.py", line 35, in _http_request
    verify=verify, cert=cert, cookies=cookies)
  File "/paas/.venv/paas/lib/python2.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/paas/.venv/paas/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/paas/.venv/paas/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/paas/.venv/paas/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/paas/.venv/paas/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='www.bking.com', port=8073): Max retries exceeded with url: /login/accounts/is_login/?bk_token=1lVUC14z2SZfsIJgs_nX_TsK7dEM6gqrbzmdTUtrG6Q (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcfdf0f7810>: Failed to establish a new connection: [Errno 111] Connection refused',))
ERROR [2022-04-12 11:00:10] /paas/paas/components/login.py 32 _call_login_api 317 140530790353640
         请求login接口失败: method=http_get, api=is_login, message=  